language: ruby
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - cp config/secrets.travis.yml config/secrets.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
