matrix:
  include:
    - language: ruby
      rvm:
        - 2.6
      cache: bundler
      services:
        - postgresql
      addons:
        postgresql: "9.6"
      before_script:
        - cp config/secrets.travis.yml config/secrets.yml
        - cp config/database.travis.yml config/database.yml
        - psql -c 'create database travis_ci_test;' -U postgres

    - language: node_js
      node_js: 10

      cache:
        directories:
          - node_modules
          - elm-stuff

      install:
        - npm install

      script:
        - npm run build
        - npx elm-format --validate app
        - npx prettier --check "app/assets/**/*.{js,jsx,scss}" "*.js"
